### ISSUE TITLE
`versions-6.0.0` fails to build with GHC 8.10 and earlier

### ISSUE THREAD

**Issue by RyanGlScott** [fosskers/versions#65]
```
$ cabal build -w ghc-8.10.7
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - versions-6.0.0 (lib) (first run)
Preprocessing library for versions-6.0.0..
Building library for versions-6.0.0..
[1 of 1] Compiling Data.Versions    ( Data/Versions.hs, /home/rscott/Documents/Hacking/Haskell/versions-6.0.0/dist-newstyle/build/x86_64-linux/ghc-8.10.7/versions-6.0.0/build/Data/Versions.o, /home/rscott/Documents/Hacking/Haskell/versions-6.0.0/dist-newstyle/build/x86_64-linux/ghc-8.10.7/versions-6.0.0/build/Data/Versions.dyn_o )

Data/Versions.hs:151:14: error:
    Not in scope: ‘NEL.singleton’
    Perhaps you meant ‘T.singleton’ (imported from Data.Text)
    Module ‘Data.List.NonEmpty’ does not export ‘singleton’.
    |
151 |     let cs = NEL.singleton . MDigit e $ showt e
    |              ^^^^^^^^^^^^^
Error: cabal: Failed to build versions-6.0.0.
```

**Comment by fosskers** [comment]
Thanks for the report. I'll take the opportunity to make CI more robust.

**Comment by fosskers** [comment]
I have released `6.0.1`.
